[tool.poetry]
name = "pulumitest-python"
version = "0.1.0"
description = ""
authors = ["Jonathan Davenport <jdavenport@pulumi.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
pulumi = "^3.187.0"
pulumi-pulumiservice = "^0.31.0"
pulumi-aws = "^7.2.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
